apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-auth-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: vault-auth
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: vault-auth-clusterrole
  apiGroup: rbac.authorization.k8s.io
