apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-auth-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "services", "replicationcontrollers", "events"]
  verbs: ["list"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "replicasets", "daemonsets"]
  verbs: ["list"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["list"]

